# Start a network of 50 nodes, of which one is a bootstrap node and the rest 
# are regular nodes that will use the bootstrap node to join the network.
#
# Use "docker compose up -d" to start the network in detached mode.
# Use "docker compose down" to stop and remove the network.

version: "3"
name: kademlia
services:
  node:
    image: docker-go
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 50
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
    environment:
      - KADEMLIA_PORT=14041
      - KADEMLIA_BOOTSTRAP_NODE=172.19.0.2:14041
      - KADEMLIA_VERBOSE=1
    networks:
      - net1

networks:
  net1:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
